apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-demo
  namespace: jenkins-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      project: www
      app: php-demo
  template:
    metadata:
      labels:
        project: www
        app: php-demo
    spec:
      containers:
      - name: nginx 
        image: firexuxiaoman/php-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080  #容器端口
          env:
        - name: branch
          value: <BRANCH_NAME>
